name: S3 Deploy
on:
  pull_request:
    types:
    - closed
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Branch checks
      run: |
        if [[ ! ( \
          "$GITHUB_HEAD_REF" == "development" && "$GITHUB_BASE_REF" == "master"
        ) ]]; then
          exit 2
        fi
    - name: Git pull existing repo
      uses: actions/checkout@v1
    - name: AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    - name: Build
      run: npm run build
    - name: Upload
      run: |
        aws configure<<EOF
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        json
        EOF
        aws s3 sync ./build ${DEPLOY_PATH}
      env:
        S3_DEPLOY_PATH: s3://production-bucket/deploy_path
